### ISSUE TITLE
Compile Nim code with optimization

### ISSUE THREAD

**Issue by sschwarzer** [yakkomajuri/fibonacci-benchmark#1]
`nim c fibonacci.nim` compiles the Nim code without optimization. For benchmarks, you should at least use `nim c -d:release fibonacci.nim`.

Here are some other settings you can try. I added some measurements from my system (with Nim 1.2.4):

Compilation | Runtime in s | Remarks
-----------------| ---------------- |-------------
nim c fibonacci.nim | 3.3 | without any runtime optimization, but faster compilation
nim c -d:release fibonacci.nim | 0.56 | with optimization
nim c -d:release -d:danger fibonacci.nim | 0.29 | without runtime checks
nim c -d:release --gc:arc fibonacci.nim | 0.31 | new memory management approach
nim c -d:release -d:danger --gc:arc fibonacci.nim | 0.30 | all combined

The last three are very similar here but this may differ for different programs.

So you can make your Nim benchmark 11 times as fast. :-) The runtime on my system is now the same as for the C version. By the way, I also tried passing `-O2` or `-O3` to the C compiler for (more) optimization, but it didn't change the timing. Probably gcc compiles with optimizations per default.

**Comment by JorySchossau** [comment]
Cool article! The graph really should be updated: for me the nim code runs a bit faster than C or a bit slower depending on the garbage collector used, which is in line with my understanding that nim-optimized C code is faster than human-optimized C code.

As sschwarzer hinted at above, users should optimize binaries for benchmarking because there is no bound on how many crazy performance-impacting things compilers can cram into the binary in the name of making your life easier for debugging. So comparing debug builds is actually comparing debug-cruft introduced by different compilers.

```sh
C Compiler: Apple Clang 10.0.0
Python: 3.7.4

C: gcc -O3 -o cfib fibonacci.c
Nim (standard GC): nim c -d:release -d:danger -o:nfib fibonacci.nim
Nim (upcoming arc GC): nim c -d:release -d:danger -o:narcfib fibonacci.nim
Python: python3 -OO fibonacci.py
```

**Comment by sschwarzer** [comment]
> As sschwarzer above said, we optimize bytecode for benchmarking

I'm not sure I said that since I'm not sure what you mean by "we" and "bytecode" in this context. :-) Do you mean the binary generated by gcc?

**Comment by JorySchossau** [comment]
As you _hinted_ at, above? :p I just wanted to further provide detail on the issue you raised.
Oh sorry, 'we' comes from too much academic writing recently! bytecode being the binary generated by gcc. [fixed]

**Comment by sschwarzer** [comment]
> As you hinted at, above? :p I just wanted to further provide detail on the issue you raised.

It's fine. I just wasn't sure what you were citing me with, i. e. if you were referring to what I *actually meant*. :-)

Now let's hope that the README (and hopefully the article on Medium) gets updated. :-)

**Comment by jibal** [comment]
> bytecode being the binary generated by gcc.

That's not what the term means.

As for the article ... people who have just learned about a language should not write about it; they are bound to get a lot of things wrong and mislead people.

**Comment by xbello** [comment]
> nim c -d:release fibonacci.nim 	0.56 	with optimization
> nim c -d:release -d:danger fibonacci.nim 	0.29 	without runtime checks
> nim c -d:release --gc:arc fibonacci.nim 	0.31 	new memory management approach
> nim c -d:release -d:danger --gc:arc fibonacci.nim 	0.30 	all combined

I believe -d:danger already includes -d:release optimizations.

**Comment by ghost** [comment]
> > nim c -d:release fibonacci.nim 	0.56 	with optimization
> > nim c -d:release -d:danger fibonacci.nim 	0.29 	without runtime checks
> > nim c -d:release --gc:arc fibonacci.nim 	0.31 	new memory management approach
> > nim c -d:release -d:danger --gc:arc fibonacci.nim 	0.30 	all combined
> 
> I believe -d:danger already includes -d:release optimizations.

Yes, that is true

**Comment by JorySchossau** [comment]
@jibal  Thanks! Fixed.

@jibal I'm concerned about the article-comment because it sounds like gatekeeping the Nim community, and yet it's so obvious there is definitely some misinformation being spread in the article, so I can see the temptation to say that. I'd like to suggest that we try not to dissuade positive enthusiasm from newcomers, because people will get things wrong by nature of being people. As long as the community is welcoming and engaging to help fix misinformation in a positive way, then this should be good for everyone. However, that's assuming the author is willing to engage, and it seems they've either abandoned this article or are on an unfortunately timed vacation or leave, leaving a bad taste for the Nim community.

**Comment by snej** [comment]
Also try ``--passC:"-flto"`` to turn on Link-Time Optimization, which can improve speed and/or code size by 10% or more. (That flag works using Clang on macOS; not sure about other compilers.)

As for the article/benchmark: Writing about cool technologies you've just discovered is great! But if you run into problems or poor performance, it's best to assume you're making a mistake and _get advice from experts_ before telling the world about those things.

**Comment by jibal** [comment]
> I'm concerned about the article-comment because it sounds like gatekeeping the Nim community,

I don't know how it can sound like gatekeeping the Nim community, since it isn't about Nim or the community and isn't from "the community", it's just my personal opinion about this sort of article from numerous past experiences. This article is actually better than most, but it still is problematic for someone who hasn't even used the language to make a presentation like this.

**Comment by sschwarzer** [comment]
@snej 
> But if you run into problems or poor performance, ...

My impression is that the author didn't even consider it "poor performance" when he saw that the Nim program was significantly faster than the Python code. I guess he just didn't expect Nim to be close to C in speed. Maybe there is an implicit assumption that a relatively little-used language wouldn't be so sophisticated to be on par with C speed.

Just my thoughts. :)

**Comment by jibal** [comment]
I suspect that's exactly right. Someone not familiar with Nim's philosophy and goals may not realize that it aims to be as performant as C (or more so), and so his benchmark is considered alarming.

**Comment by yakkomajuri** [comment]
This is great guys. I am not hiding the fact I'm a complete beginner to Nim - that was the point of the article. I'll add a mention to this there and update the repo.

**Comment by yakkomajuri** [comment]
> @jibal I'm concerned about the article-comment because it sounds like gatekeeping the Nim community, and yet it's so obvious there is definitely some misinformation being spread in the article, so I can see the temptation to say that. I'd like to suggest that we try not to dissuade positive enthusiasm from newcomers, because people will get things wrong by nature of being people. As long as the community is welcoming and engaging to help fix misinformation in a positive way, then this should be good for everyone. However, that's assuming the author is willing to engage, and it seems they've either abandoned this article or are on an unfortunately timed vacation or leave, leaving a bad taste for the Nim community.

This is a very important point by the way. Newcomers (like me) will get things wrong. Being welcoming is the way to go and I thank you all for this thread.

**Comment by yakkomajuri** [comment]
@sschwarzer Thank you for this. Added an edit to the article and updated the repo.
